### ISSUE TITLE
代码生产器生产的前端Vue代码中没有add  等按钮的代码

### ISSUE THREAD

**Issue by ajw333** [iamoldli/NetModular#10]
代码生产器生产的前端Vue代码中没有add  等按钮的代码

**Comment by iamoldli** [comment]
有的吧，你说的是没有页面文件，还是没有属性

**Comment by ajw333** [comment]
添加add的vue中没有相应的属性代码，mould{}中空的了------------------ 原始邮件 ------------------
发件人: "OLDLI"<notifications@github.com>
发送时间: 2019年7月14日(星期天) 中午12:42
收件人: "iamoldli/NetModular"<NetModular@noreply.github.com>;
抄送: "ajw333"<361072715@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [iamoldli/NetModular] 代码生产器生产的前端Vue代码中没有add  等按钮的代码 (#10)



有的吧，你说的是没有页面文&#x4EF6;，还是没有属性
 
&mdash;

**Comment by ajw333** [comment]
model: {
        },
        rules: {
        }
      },这部分空得了

**Comment by iamoldli** [comment]
model里面的属性是需要在类的模型中配置的，rules暂时没有实现
