### ISSUE TITLE
代码生成器生成的代码

### ISSUE THREAD

**Issue by ajw333** [iamoldli/NetModular#11]
icon: 'add',
        action: api.add,
        model: {
这部分没有数据
        },
        rules: {
这部分没有数据       }
      },

在api中没有相应的addimport { http } from 'nm-lib-utils'
const root = 'Blog/Article/'
const crud = http.crud(root)

export default {
没有调用
  ...crud
}
后面也没有post等方法

**Comment by iamoldli** [comment]
1、model里面的属性要在代码生成器的模型中配置
2、rules就是空的，没有实现
3、CRUD方法已经封装在了http组件里面，就是上面的 `const crud = http.crud(root)`
