### ISSUE TITLE
你好，请教两个问题

### ISSUE THREAD

**Issue by alasai** [iamoldli/NetModular#19]
dotnet watch run 是运行接口端
npm run serve 是运行vue界面
有两个问题请教：
1.如果我想对本地netcore程序调试，应该怎么操作
2.vue开发是在vs2017里还是单独用vscode打开开发

**Comment by iamoldli** [comment]
后端可以直接在vs里面启动，如果用dotnet watch run运行的话，可以通过附加进程调试，附加的时候搜索dotnet进程，第一个就是，vue开发建议vscode，不是一般的爽~
前端项目里面已经包含了一些配置信息.vscode，代码格式化什么的都已经配置好了，不过要安装ESLint和Prettier两个插件

**Comment by alasai** [comment]
嗯，现在netcore可以调试，请问vscode里面的打开的话，打开文件夹选择的路径是哪个呢，那两个插件我已经安装了

**Comment by alasai** [comment]
这项目里分成五六个模块，我得用vscode打开多个吗，可以只打开一次vscode，看到所有项目吗
