### ISSUE TITLE
sqlserver 2008 分页问题

### ISSUE THREAD

**Issue by alasai** [iamoldli/NetModular#20]
根据你的指示，修改了SqlServerAdapter.cs里面的代码
sql = string.Format("select * from (select row_number() over(order by {0}) as Rownum,{1} from {2} where {3}) as T where T.Rownum between {4} and {5}", sort, select, table, where, skip, take);

运行查询分页就会报错，
order by  id 字段不明确
比如生成代码如下
![图片](https://user-images.githubusercontent.com/26901102/63992241-8bb69680-cb1d-11e9-8406-25afcc9e33dd.png)
这个是程序字段生成的，我怎么控制呢

**Comment by iamoldli** [comment]
我已经添加了2008版本的支持，你更下代码试下吧
更新日志：https://nm.iamoldli.com/docs/update/2019-08-30.html
