### ISSUE TITLE
使用IDistributedCache替换ICacheHandler?

### ISSUE THREAD

**Issue by ZUOXIANGE** [iamoldli/NetModular#23]
然后扩展一些泛型方法支持,这样会不会更官方一点?

**Comment by ZUOXIANGE** [comment]
另外数据访问的封装能不能单独抽离一个开源项目并完善一下使用说明啊

**Comment by iamoldli** [comment]
我看了下`IDistributedCache`提供的方法比较少，它的值是byte[]类型的，自己还是要经过一层封装，而且感觉不好扩展。
其实业务中如果缓存的东西比较多，就不再使用ICacheHandler了，都是直接通过RedisHelper来操作了。

**Comment by iamoldli** [comment]
其实数据库Data模块最早是一个单独的开源项目，后来集成到一起了，后面会考虑抽象拆分，以便能够支持其它的ORM

**Comment by ZUOXIANGE** [comment]
好的,了解
