### ISSUE TITLE
模块问题

### ISSUE THREAD

**Issue by joesdar** [iamoldli/NetModular#26]
我使用页面中的开发工具创建模块后，模块文件夹更名为nm开头的，放到node_module中，运行serve
点击同步模块，在创建菜单的时候，先创建了节点菜单，然后再创建子节点，选择路由菜单的时候，选择新模块，但是选择路由里面没有内容

**Comment by joesdar** [comment]
还有个问题 生成内容乱码

**Comment by iamoldli** [comment]
前端模块需要在main.js里面导入

**Comment by joesdar** [comment]
根目录下面的main.js，我修改了啊

**Comment by joesdar** [comment]
原来我没有addModule 真是无语了，，，，，

乱码咋办，是不是我用Mac的原因？？

**Comment by iamoldli** [comment]
乱码你可以看看代码生成器里面对应的t4模板文件是否也是乱码

**Comment by joesdar** [comment]
生成器中的模板不是乱码
