### ISSUE TITLE
bug host

### ISSUE THREAD

**Issue by chylove1982** [iamoldli/NetModular#28]
开发模式和线上运营模式的host.josn 端口号不同但是并没有生效。
host.josn 
{
    //地址
    "Urls": "http://*:8093",
    //开启Swagger
    "Swagger": true
}
host.Development.json
{
    //地址
    "Urls": "http://*:6220",
    //开启Swagger
    "Swagger": true
}

**Comment by iamoldli** [comment]
host.json文件是构造Host的时候读取的，这个时候还没办法获取环境变量，所以虽然我保留的这种结构，但是host.Development.json是读取不到的，到现在也没找到解决办法~

**Comment by chylove1982** [comment]
明白 了！我先关闭了？
