### ISSUE TITLE
CS8107	C# 7.0 中不支持功能“默认文本”。请使用 7.1 或更高的语言版本。

### ISSUE THREAD

**Issue by BigBigXiong** [iamoldli/NetModular#3]
解决方法1：项目右键属性 ---> 生成 ---> 找到最下面的高级按钮，点击高级按钮 ---> 常规 ---> 语言版本 ---> 选择 C#最新次要版本，或者比当前版本更高的版本即可，点击确定，然后保存即可。

解决方法2: 在各targets文件添加
`<PropertyGroup>
    <LangVersion>latest</LangVersion>
</PropertyGroup>
`

**Comment by iamoldli** [comment]
谢谢提醒，已经在Directory.Build.props添加了该配置项~

**Comment by leeolevis** [comment]
RabbitMQ测试项目还没配置么
