### ISSUE TITLE
无法找到项目引用的包

### ISSUE THREAD

**Issue by DUWENINK** [iamoldli/NetModular#4]
我建立了一个如图所示的项目,然后点击生成![image](https://user-images.githubusercontent.com/16337239/58630585-7493bd00-8312-11e9-93c4-698697e03dda.png)

生成的项目中的csproj里边有大量的
![image](https://user-images.githubusercontent.com/16337239/58630635-9725d600-8312-11e9-8c78-3d9d4ec8c418.png)
这些包因为nuget上边没有因此我也无法运行我新建的代码,天呐,这可真是太糟糕了

**Comment by DUWENINK** [comment]
上边的问题前缀改成Nm就好,
但是我运行前端代码的时候出现了这个问题 
![image](https://user-images.githubusercontent.com/16337239/58632608-a576f080-8318-11e9-8c2f-cc9a8f0a3ec4.png)

**Comment by iamoldli** [comment]
@DUWENINK 执行下npm i试试

**Comment by iamoldli** [comment]
后端引用的包前缀要使用Nm，除非自己修改代码重新发布，前端的项目需要先执行npm i 安装依赖包，在 执行 npm update 更新包，这个是我文档的时候疏忽了，已修改

**Comment by DUWENINK** [comment]
![image](https://user-images.githubusercontent.com/16337239/58632862-7dd45800-8319-11e9-930f-9817bc2a2214.png)  执行 npm i  之后发现有一个包 nm-lib-skins 找不到

**Comment by iamoldli** [comment]
@DUWENINK 你的npm是不是用了国内的镜像了，nm-lib-skins包我已经发布到npm.js了

**Comment by DUWENINK** [comment]
![image](https://user-images.githubusercontent.com/16337239/58633101-110d8d80-831a-11e9-91d7-6b7908761965.png)
是的用了国内的,国内的版本只到1.0.4  还有两个报错, 貌似是找不到这两个npm包,希望作者可以帮我排查下是否是代码变量拼接有问题

> @DUWENINK 你的npm是不是用了国内的镜像了，nm-lib-skins包我已经发布到npm.js了

**Comment by iamoldli** [comment]
@DUWENINK 应该是国内的镜像没做同步，最新的nm-lib-skins版本是1.1.0，至于上面图片中的警告，是你自己项目里面package.json为配置相应的参数，可以忽略

**Comment by iamoldli** [comment]
用这个命令安装一下 npm install -g nm-lib-skins --registry=https://registry.npmjs.org

**Comment by DUWENINK** [comment]
> @DUWENINK 应该是国内的镜像没做同步，最新的nm-lib-skins版本是1.1.0，至于上面图片中的警告，是你自己项目里面package.json为配置相应的参数，可以忽略

全部都安装好了但是有两个警告,这两个包我没有啊,请问我要忽略这两个警告吗

**Comment by DUWENINK** [comment]
![image](https://user-images.githubusercontent.com/16337239/58641349-99495e00-832d-11e9-9d45-e0667662f204.png)
换了国外的源,下载出现了这个情况

**Comment by iamoldli** [comment]
@DUWENINK 警告不用管

**Comment by DUWENINK** [comment]
Thanks ,I close it
