### ISSUE TITLE
前端页面项目启动失败

### ISSUE THREAD

**Issue by gggetgso** [iamoldli/NetModular#40]
前端项目到第三步run时，提示失败，有这三个错误，node.js版本v12.14

* ./custom in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/config/index/index.vue?vue&type=script&lang=js&
* ./form in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/config/index/module/index.vue?vue&type=script&lang=js&
* ./system in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/config/index/index.vue?vue&type=script&lang=js&

**Comment by iamoldli** [comment]
你好，有几个文件被忽略了没有提交，我已经补上了

**Comment by js0007** [comment]
今天试了一下，这个问题还存在
