### ISSUE TITLE
系统配置 - 配置管理 - 模块配置 - 代码生成中的“ 模块前缀”和“ 前端组件前缀”，好像写固定了，不能修改配置。

### ISSUE THREAD

**Issue by qingsongyoudao** [iamoldli/NetModular#42]

**Comment by iamoldli** [comment]
我试过了，可以修改的，你再看看线上demo~

**Comment by qingsongyoudao** [comment]
刚才试了线上的Demo没问题，我本地部署的保存出错，提示与管理员联系。刚才查询了数据库，没有看到相关保存记录，请问是不是在config这个表中，没有找到相亲记录，是不是由于初始化原因，没有写入？

**Comment by iamoldli** [comment]
看看日志包的什么错~

**Comment by iamoldli** [comment]
之前模块配置保存有问题，保存后容器中的配置实例会更新，但是持久化的时候没有提交事务导致未成功持久化，该bug已修复~

**Comment by qingsongyoudao** [comment]
可以了
