### ISSUE TITLE
菜单树搜索结果不正确(已更正) 问题描述改成:grid高度问题 

### ISSUE THREAD

**Issue by DUWENINK** [iamoldli/NetModular#5]
![image](https://user-images.githubusercontent.com/16337239/58759313-620bc480-855a-11e9-9078-00877556ed2e.png)
如图所示,w我点击节点之后应该出现`所有子节点`,但是右侧列表只出现了第一个

**Comment by DUWENINK** [comment]
> ![image](https://user-images.githubusercontent.com/16337239/58759313-620bc480-855a-11e9-9078-00877556ed2e.png)
> 如图所示,w我点击节点之后应该出现`所有子节点`,但是右侧列表只出现了第一个

补充下,生成后的项目发现的问题

**Comment by DUWENINK** [comment]
![image](https://user-images.githubusercontent.com/16337239/58759487-7604f580-855d-11e9-88d3-4ab521643d23.png)
生成的项目中 grid 没有占满表格

**Comment by DUWENINK** [comment]
![image](https://user-images.githubusercontent.com/16337239/58759500-a0ef4980-855d-11e9-831c-b08c31893be2.png)
生成的项目中 grid 没有占满表格`子页面`

**Comment by iamoldli** [comment]
@DUWENINK 是不是浏览器兼容问题，按理讲不应该这样的

**Comment by DUWENINK** [comment]
> @DUWENINK 是不是浏览器兼容问题，按理讲不应该这样的

不是,我得Chrome是最新版本的,而且我在console里边看高度是100px,这个问题可以先Pending,我今晚有空再看一下重新提交issue

**Comment by iamoldli** [comment]
找到问题了，是因为ElementUI最新版本表格默认高度从100%改为了100px导致的，已经调整nm-lib-skins并发布1.1.1版本到npm仓库了，直接更新前端代码即可
