### ISSUE TITLE
丰富Cloud.QiNiu

### ISSUE THREAD

**Issue by GHCoder-SSC** [iamoldli/NetModular#54]
主要功能
七牛空间图片上传（主要还是图片吧，其他大文件的可以不需要）；
提供图片样式接口（可能描述的不好），根据自己在七牛空间定义的样式，组装图片URL，比如原图或者指定大小的图片。
兼容好各区域的上传接口（之前七牛上传的不同地域的sdk不一样，比如华南的sdk不能用于华东的空间上传，不知道现在这个兼容问题七牛有没有完善好）

**Comment by iamoldli** [comment]
这个暂时不在本框架的范围内，请自行封装~
