### ISSUE TITLE
希望提供一个token的维护扩展

### ISSUE THREAD

**Issue by GHCoder-SSC** [iamoldli/NetModular#55]
admin提供token维护的接口；业务模块实现。
目的是让所有能拿到token的用户都能访问相关接口，且拿到token的方式不仅局限于账号密码/手机验证码等方式；还包括微信扫码登录，第三方授权登录（后期可以用id4实现，不过和本扩展并不矛盾），各种登录的主要目的就是拿到token；所以希望admin能提供token维护的扩展。

**Comment by GHCoder-SSC** [comment]
持续关注中....

**Comment by iamoldli** [comment]
已添加多种登录方式
