### ISSUE TITLE
666星了，替你记录下~文档速度跟不上了，加油啊

### ISSUE THREAD

**Issue by o7z** [iamoldli/NetModular#56]
在NetModular中，约定所有的配置信息按照其功能放到不同的文件中，所有配置文件放到 config 目录下，而不是把所有配置信息都放在 appsettings.json 文件里面。而且每个配置文件都包括生产环境(db.json)和开发环境(db.Development.json)两个文件。

**Comment by iamoldli** [comment]
尴尬～
