### ISSUE TITLE
权限管理和断点调试问题

### ISSUE THREAD

**Issue by DUWENINK** [iamoldli/NetModular#6]
![image](https://user-images.githubusercontent.com/16337239/59101965-425f0c80-895d-11e9-9af9-929634a1006d.png)

如图,我已经是管理员了,但是查询的时候显示没有权限,403错误,并且我swagger调试附加了token仍然进不去断点,但是有返回信息
![image](https://user-images.githubusercontent.com/16337239/59102020-67537f80-895d-11e9-81e2-cd7976bd74c8.png)
返回信息还是报告403错误
![image](https://user-images.githubusercontent.com/16337239/59102055-881bd500-895d-11e9-9ca2-142fbaaeba02.png)

**Comment by iamoldli** [comment]
每一个action代表一个权限，菜单或者按钮都要在后台绑定它用到的权限，比如一般列表页需要关联对应的Query权限，当给角色分配菜单或按钮的时候，系统内部会默认将菜单或按钮关联的权限与角色进行管理，你看看你的那个页面有没有绑定权限

**Comment by DUWENINK** [comment]
`每一个action代表一个权限，菜单或者按钮都要在后台绑定它用到的权限`--你好我想问一下你说的后台是指截图上的权限管理中吗

**Comment by DUWENINK** [comment]
谢谢作者~我在菜单里边配置好了之后发现可以使用了
