### ISSUE TITLE
orm查询问题

### ISSUE THREAD

**Issue by hajiuxbz** [iamoldli/NetModular#61]
query.Where(m => m.id==123)
                .LeftJoin<T2>((x, y) => x.pid== y.Id)
                .Select((t1,t2)=> new { t1,  t1.p = t2})
                .ToListAsync();

class t1{
  id
  string xxx
 t2 ddd
}

class t2{
id  
string name
}

这两个实体是关联的 在关联查询时不能直接把t2 加在t1的ddd吗 我测试普通属性是支持的但是换为对象就不支持了

**Comment by iamoldli** [comment]
不支持导航属性~

**Comment by hajiuxbz** [comment]
那一对多 一对一只能多次查询嘛？

**Comment by iamoldli** [comment]
子查询或者连接查询，导航属性会让代码不好控制，所以没有实现这个功能

**Comment by hajiuxbz** [comment]
好吧 ~谢谢
