### ISSUE TITLE
租客模式

### ISSUE THREAD

**Issue by lable** [iamoldli/NetModular#68]
胡乱说：
可否考虑以模块增加租客模式，毕竟租客模式下，也需要有一个总后台来管理？
一、ILoginClaimsExtendProvider扩展jwt记录租客id；
二、增加字段模式：使用条件拦截增加where条件；
三、分表模式：表名_租客代码
四、分库模式：数据库连接字符串_租客代码

**Comment by iamoldli** [comment]
一二两点已经实现，可以测试了
