### ISSUE TITLE
求问actions取值方式，并且为何仅获取到admin下的api

### ISSUE THREAD

**Issue by songjt123** [iamoldli/NetModular#85]
netmodular-ui下packages->index.js 文件
我新定义一个请求方式，但是不是在admin中的api，在新模块的api中，然后根据源码案例新增一个getLatestNotice请求
system.js里面定义为null

 actions: {
      /** 登录 */
      login: null,
      /** 获取验证码 */
      getVerifyCode: null,
      /**刷新令牌 */
      refreshToken: null,
      /**获取认证信息 */
      getAuthInfo: null,
      /** 修改密码 */
      updatePassword: null,
      /** 保存皮肤配置信息 */
      saveSkin: null,
      /** 获取最新通知 */
      getLatestNotice: null
    }

index.js 里面加载出actions的属性
 // 系统属性
    let system = {
      modules: modules.map(m => m.module),
      customToolbars: customToolbars,
      globalComponents: globalComponents.map(m => m.name),
      actions
    }
不知道过程中怎么取值的
system.js里面定义的系统api方法是否可以获取到其他项目中的api，截图上传不了，见谅
getAuthInfo: () => { return $http.get(urls.getAuthInfo) }
getLatestNotice: null

**Comment by iamoldli** [comment]
说一下需求，为什么要在system.js里面增加属性~

**Comment by songjt123** [comment]
也是想做演示地址里面的弹出消息通知，根据demo已经把组件加载进了代码里，但是请求方式这块根据已有的iframe页组件，我看到是写在system.js中定义的actions，但是经过长时间调试，发现只能从netmodular-ui-admin的api下取到请求方式，所以想请教一下api那块怎么能取到我现有模块定义的请求方式


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iamoldli/NetModular"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 下午5:53
收件人:&nbsp;"iamoldli/NetModular"<NetModular@noreply.github.com&gt;;
抄送:&nbsp;"之外"<2198668022@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iamoldli/NetModular] 求问actions取值方式，并且为何仅获取到admin下的api (#85)





 
说一下需求，为什么要在system.js里面增加属性~

**Comment by iamoldli** [comment]
还是没明白，你自己模块里面的api，为什么要放到system.js里面

**Comment by songjt123** [comment]
我现在在做您demo里面的广告招租弹出层，那块源码里面数据是写死的，我想通过请求调用我现有模块的部分数据，但发现只能取到admin里面的api         
            
                
                    
                            
                                
                            
                            
                                219866802
                            
                    
                        
                            
                                    邮箱：2198668022@qq.com
                            
                        
                
            
        在2020年12月17日 20:13，OLDLI 写道： 

还是没明白，你自己模块里面的api，为什么要放到system.js里面



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/iamoldli/NetModular/issues/85#issuecomment-747402979",

"url": "https://github.com/iamoldli/NetModular/issues/85#issuecomment-747402979",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by songjt123** [comment]
我尝试在system.js里面直接引入另一个项目的API，发现这种方式行不通         
            
                
                    
                            
                                
                            
                            
                                2198668022
                            
                    
                        
                            
                                    邮箱：2198668022@qq.com
                            
                        
                
            
        在2020年12月17日 20:13，OLDLI 写道： 

还是没明白，你自己模块里面的api，为什么要放到system.js里面



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/iamoldli/NetModular/issues/85#issuecomment-747402979",

"url": "https://github.com/iamoldli/NetModular/issues/85#issuecomment-747402979",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by iamoldli** [comment]
首先，不建议在system.js里面添加业务相关的功能。

其次，NetModular.UI是一个针对管理系统开发的框架，它本身不包含任何后端接口能力，而是提供了对应的配置能，如system中的actions，包含了管理系统所需的一些方法：

```js
        /**系统的api方法 */
    actions: {
      /** 登录 */
      login: null,
      /** 获取验证码 */
      getVerifyCode: null,
      /**刷新令牌 */
      refreshToken: null,
      /**获取认证信息 */
      getAuthInfo: null,
      /** 修改密码 */
      updatePassword: null,
      /** 保存皮肤配置信息 */
      saveSkin: null
    }
```

NetModular.UI本身没有但是需要这些方法，所以需要在使用它的地方来配置，而NetModular则是在Admin模块中进行配置的。

如果你确实需要在system.js里面新增你的方法，可以试一下在你自己的模块的index.js的callback中配置，参考如下：

```js
import './api'
import store from './store'
import routes from './routes'
import components from './components'
import module from './module'

export default {
  module,
  routes,
  store,
  components,
  callback({ store }) {
    store.state.app.system.actions.test = () => {
      console.log(1)
      //这里写你的逻辑
    }
  }
}
```

**Comment by songjt123** [comment]
收到回复，感谢解答，我这边会再考虑一下是否按照我现有的思路去修改         
            
                
                    
                            
                                
                            
                            
                                2198668022
                            
                    
                        
                            
                                    邮箱：2198668022@qq.com
                            
                        
                
            
        在2020年12月17日 21:08，OLDLI 写道： 

首先，不建议在system.js里面添加业务相关的功能。

其次，NetModular.UI是一个针对管理系统开发的框架，它本身不包含任何后端接口能力，而是提供了对应的配置能，如system中的actions，包含了管理系统所需的一些方法：

        /**系统的api方法 */

    actions: {

      /** 登录 */

      login: null,

      /** 获取验证码 */

      getVerifyCode: null,

      /**刷新令牌 */

      refreshToken: null,

      /**获取认证信息 */

      getAuthInfo: null,

      /** 修改密码 */

      updatePassword: null,

      /** 保存皮肤配置信息 */

      saveSkin: null

    }

NetModular.UI本身没有但是需要这些方法，所以需要在使用它的地方来配置，而NetModular则是在Admin模块中进行配置的。

如果你确实需要在system.js里面新增你的方法，可以试一下在你自己的模块的index.js的callback中配置，参考如下：

import './api'

import store from './store'

import routes from './routes'

import components from './components'

import module from './module'



export default {

  module,

  routes,

  store,

  components,

  callback({ store }) {

    store.state.app.system.actions.test = () => {

      console.log(1)

      //这里写你的逻辑

    }

  }

}



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/iamoldli/NetModular/issues/85#issuecomment-747428864",

"url": "https://github.com/iamoldli/NetModular/issues/85#issuecomment-747428864",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
