### ISSUE TITLE
Chinese characters become ? when init database on Sql Server

### ISSUE THREAD

**Issue by riverstore** [iamoldli/NetModular#96]
Hi, First thanks a lot for the great project.

I run project with Sql Server 2016 Express, Windows 10, Chinese characters become to ? character. Please see image

![Screenshot](https://i.imgur.com/mA1Fg1t.png)

Please help to fix it. 
Thanks a lot.

**Comment by iamoldli** [comment]
you have to set or change the database collation  `Chinese_PRC_CI_AS`

![QQ截图20210228232300](https://user-images.githubusercontent.com/7851430/109423842-0d8dc580-7a1c-11eb-98af-130fdcd58d92.png)
